### PR TITLE
Update replace.md

### PR DESCRIPTION
**Pull request by jngdan**
Hello,
I kindly suggest to replace the current documentation of this function 'Replace' by this proposal. I published it on the Community Forum (see here : https://community.jeedom.com/t/tuto-de-la-bonne-utilisation-de-loutil-remplacer/125294/1), and all comments I received was positive. It's seems obvious that the official documentation is currently not enough precise and clear, and could be confused.  As this function is very powerful, but also dangerous for the health system due to is deeply commitment, I think it's very important to be accurate at all steps for everybody for a good use of it. Thanks,
Daniel

### Related issues/external references

Fixes #

## Types of changes

- [ ] Bug fix _(non-breaking change which fixes)_
- [ ] New feature _(non-breaking change which adds functionality)_
- [ ] Breaking change _(fix or feature that would cause existing functionality to change)_
    - [ ] This change is only breaking for integrators, not for external standards or end-users.
- [x] Documentation improvement

## PR checklist

- [x] I have checked there is no other PR open for the same change.
- [x] I have read the [[La ligne directrice pour contribuer à ce projet / Contribution guidelines for this project](.github/CONTRIBUTING.md)).
- [x] I grant the project the right to include and distribute the code under the GNU.
- [x] I have added tests to cover my changes.
- [x] I have verified that the code complies with the projects coding standards.
- [x] [Required for new sniffs] I have added MD documentation for the sniff.

### CODE REVIEW

**Comment by Sekiro-kost** [comment]
A useful PR. Great job

**Review by Sekiro-kost — APPROVED** [review]

**Comment by Furaxworld** [comment]
@Sekiro-kost 

Hello,

Yes great PR but I think this must be done directly in the core so as not to be overwritten when the bot passes.

**Comment by Sekiro-kost** [comment]
> @Sekiro-kost
> 
> Hello,
> 
> Yes great PR but I think this must be done directly in the core so as not to be overwritten when the bot passes.


@zoic21  what is your opinion ?

**Comment by Furaxworld** [comment]
@Sekiro-kost 
image

**Comment by Sekiro-kost** [comment]
> @Sekiro-kost image
> 
> `fr_FR/core/4.4/replace`

Je n’avais encore jamais géré cette partie 
Je laisse mes collègues gérer ça 
😉

**Review by zoic21 — APPROVED** [review]

**Comment by zoic21** [comment]
I'am ok but you must do this PR on alpha branch.

**Pull request closed without merging**
